name: Update Google Reviews

on:
  # Run automatically every day at 2 AM UTC
  schedule:
    - cron: "0 2 * * *"

  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch latest reviews from Google
        env:
          GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
          PLACE_QUERY: "Percetakan gemiprint Cifest Walk Cikarang"
        run: node ./tools/fetch-reviews.mjs

      - name: Commit updated reviews.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet reviews.json; then
            echo "No changes to reviews.json"
          else
            git add reviews.json
            git commit -m "chore: update Google reviews [skip ci]"
            git push
          fi
